### PR TITLE
Task2 completed

### PR DESCRIPTION
**Pull request by DhruvHeisenberg**
Issue: 46

### CODE REVIEW

**Comment by Manav1410** [comment]
Wrong link in file

**Comment by DhruvHeisenberg** [comment]
Respected sir,
Sir actually I have checked my mail right now and I got to know that I had
provided wrong link in the file so sir is there anything I could do so that
my task is accepted?
Thank you
Regards
Dhruv Tripathi

**Comment by Manav1410** [comment]
@DhruvHeisenberg comment your figma link here. We will check it once and allot points accordingly

**Comment by DhruvHeisenberg** [comment]
https://www.figma.com/file/fpftztjKLwuD6WazAlaz5C/UI-Workshop---Hands-on-kit?node-id=0%3A1

**Pull request closed without merging**
